apiVersion: apps/v1
kind: Deployment
metadata:
  name: minfi-services-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minfi-service
  template:
    metadata:
      labels:
        app: minfi-service
    spec:
      #nodeSelector:
      #  kubernetes.io/hostname: ip-000-000-000-000.us-east-2.compute.internal
      containers:
      - name: minfi-service
        image: ghcr.io/rabellino/minfi-service:prod
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 125m
        ports:
          - containerPort: 8080
            name: service
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-dockerconfig